# Generated by Django 5.0.4 on 2024-04-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarra', models.CharField(max_length=666)),
                ('nombre', models.CharField(max_length=666)),
                ('categoria', models.CharField(max_length=666)),
                ('precioUnitario', models.CharField(max_length=666)),
            ],
        ),
    ]
